Repository SoyEtiago/Proyecto-EDyA2, pull requests merged in 2024-10, with the labels that each got.

#12 Establish connection to Firebase
  backend/database/firebaseConnection.js
  backend/package-lock.json
  backend/package.json
  backend/server/server.js
Labels: documentation, enhancement

#14 NEEDS DEBUG and finish a correct implementation
  backend/controllers/auth.js
  backend/database/connection.js
  backend/database/firebaseConnection.js
  backend/main.js
  backend/models/users.js
  backend/package-lock.json
  backend/package.json
  backend/routes/auth.js
  backend/routes/home.js
  backend/server/server.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/config/firebase.js
  frontend/src/firebase/firebase.js
Labels: enhancement, help wanted

#19 Backend implementation Live session coding with team
  backend/app.js
  backend/controllers/authController.js
  backend/controllers/eventoController.js
  backend/db/dbConnection.js
  backend/firebase/firebaseConnection.js
  backend/middlewares/authMiddleware.js
  backend/middlewares/invalidPathHandler.js
  backend/middlewares/reqLog.js
  backend/models/eventoModel.js
  backend/models/users.js
  backend/models/usuarioModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/authRoute.js
  backend/routes/eventoRoute.js
Labels: enhancement

#20 v0.3.0 Refactor authentication middleware and validation
  backend/app.js
  backend/controllers/authController.js
  backend/db/dbConnection.js
  backend/db/firebaseConnection.js
  backend/middlewares/authMiddleware.js
  backend/routes/authRoute.js
  backend/routes/eventoRoute.js
Labels: enhancement

#22 Add registration route to the React Router
  frontend/src/App.jsx
  frontend/src/page/Register.jsx
Labels: enhancement, good first issue

#24 Cambios Frontend
  frontend/src/App.jsx
  frontend/src/Layouts/Layout.jsx
  frontend/src/components/Event.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/Valoraciones.jsx
  frontend/src/page/HomePage.jsx
  frontend/src/page/infoEvento.jsx
Labels: enhancement

#23 Implement transactions to feature and fix registration and login logic
  backend/app.js
  backend/controllers/authController.js
  backend/controllers/eventoController.js
  backend/db/dbConnection.js
  backend/middlewares/authMiddleware.js
  backend/models/eventoModel.js
  backend/models/usuarioModel.js
  backend/package-lock.json
  backend/routes/authRoute.js
  frontend/eslint.config.js
Labels: enhancement
